export const NKRouter = {
    dashboard: () => '/dashboard',
    menu: {
        list: () => '/dashboard/menu',
    },
    auth: {
        forgotPassword: () => '/auth/forgot-password',
        view: () => '/dashboard/auth/view',
        edit: () => '/dashboard/auth/edit'
    },
    user: {
        list: () => '/dashboard/user',
        create: () => '/dashboard/user/create',
        edit: (id: number) => `/dashboard/user/${id}/edit`,
        detail: (id: number) => `/dashboard/user/${id}`,
    },
    highSchool: {
        list: () => '/dashboard/high-school',
        create: () => '/dashboard/high-school/create',
        edit: (id: number) => `/dashboard/high-school/${id}/edit`,
        detail: (id: number) => `/dashboard/high-school/${id}`,
    },
    classGroup: {
        list: () => '/dashboard/class-group',
        create: () => '/dashboard/class-group/create',
        edit: (id: number) => `/dashboard/class-group/${id}/edit`,
        detail: (id: number) => `/dashboard/class-group/${id}`,
    },
    classes: {
        list: () => '/dashboard/classes',
        create: () => '/dashboard/classes/create',
        edit: (id: number) => `/dashboard/classes/${id}/edit`,
        detail: (id: number) => `/dashboard/classes/${id}`,
        history: (id: number) => `/dashboard/classes/${id}/history`,
    },
    schoolYear: {
        list: () => '/dashboard/school-year',
        create: () => '/dashboard/school-year/create',
        edit: (id: number) => `/dashboard/school-year/${id}/edit`,
        detail: (id: number) => `/dashboard/school-year/${id}`,
    },
    schoolAdmin: {
        list: () => '/dashboard/school-admin',
        create: () => '/dashboard/school-admin/create',
        edit: (id: number) => `/dashboard/school-admin/${id}/edit`,
        detail: (id: number) => `/dashboard/school-admin/${id}`,
    },
    students: {
        list: () => '/dashboard/students',
        create: () => '/dashboard/students/create',
        edit: (id: number) => `/dashboard/students/${id}/edit`,
        detail: (id: number) => `/dashboard/students/${id}`,
    },
    teachers: {
        list: () => '/dashboard/teachers',
        create: () => '/dashboard/teachers/create',
        edit: (id: number) => `/dashboard/teachers/${id}/edit`,
        detail: (id: number) => `/dashboard/teachers/${id}`,
    },
    times: {
        list: () => '/dashboard/times',
        create: () => '/dashboard/times/create',
        edit: (id: number) => `/dashboard/times/${id}/edit`,
        detail: (id: number) => `/dashboard/times/${id}`,
    },
    violations: {
        list: () => '/dashboard/violations',
        create: () => '/dashboard/violations/create',
        edit: (id: number) => `/dashboard/violations/${id}/edit`,
        detail: (id: number) => `/dashboard/violations/${id}`,
        createForStudent: () => `/dashboard/violations/create-student`,
        createForSupervisor: () => `/dashboard/violations/create-supervisor`,
        history: (id: number) => `/dashboard/violations/${id}/history`,
    },
    violationGroup: {
        list: () => '/dashboard/violation-groups',
        create: () => '/dashboard/violation-groups/create',
        edit: (id: number) => `/dashboard/violation-groups/${id}/edit`,
        detail: (id: number) => `/dashboard/violation-groups/${id}`,
    },
    violationType: {
        list: () => '/dashboard/violation-types',
        create: () => '/dashboard/violation-types/create',
        edit: (id: number) => `/dashboard/violation-types/${id}/edit`,
        detail: (id: number) => `/dashboard/violation-types/${id}`,
    },
    violationConfig: {
        list: () => '/dashboard/violation-configs',
        create: () => '/dashboard/violation-configs/create',
        edit: (id: number) => `/dashboard/violation-configs/${id}/edit`,
        detail: (id: number) => `/dashboard/violation-configs/${id}`,
    },
    violationTop: {
        inWeek: () => '/dashboard/violation-tops/violation-in-week',
        inClass: () => '/dashboard/violation-tops/violation-in-class',
        inYear: () => '/dashboard/violation-tops/violation-in-year',
        topClass: () => '/dashboard/violation-tops/violation-top-class',
        topStudent: () => '/dashboard/violation-tops/violation-top-student',
        topStudentInClass: () => '/dashboard/violation-tops/violation-top-studentInClass',
        violationChart: () => '/dashboard/violation-tops/violation-chart',
    },
    yearPackage: {
        list: () => '/dashboard/year-packages',
        create: () => '/dashboard/year-packages/create',
        edit: (id: number) => `/dashboard/year-packages/${id}/edit`,
        detail: (id: number) => `/dashboard/year-packages/${id}`,
    },
    evaluation: {
        list: () => '/dashboard/evaluations',
        create: () => '/dashboard/evaluations/create',
        edit: (id: number) => `/dashboard/evaluations/${id}/edit`,
        detail: (id: number) => `/dashboard/evaluations/${id}`,
    },
    evaluationTop: {
        list: () => '/dashboard/evaluation-tops/',
    },
    evaluationDetail: {
        list: () => '/dashboard/evaluation-details',
        create: () => '/dashboard/evaluation-details/create',
        edit: (id: number) => `/dashboard/evaluation-details/${id}/edit`,
        detail: (id: number) => `/dashboard/evaluation-details/${id}`,
    },
    package: {
        list: () => '/dashboard/packages',
        buy: () => '/dashboard/packages/buy-packages',
        create: () => '/dashboard/packages/create',
        edit: (id: number) => `/dashboard/packages/${id}/edit`,
        detail: (id: number) => `/dashboard/packages/${id}`,
    },
    schoolConfig: {
        list: () => '/dashboard/school-configs',
        create: () => '/dashboard/school-configs/create',
        edit: (id: number) => `/dashboard/school-configs/${id}/edit`,
        detail: (id: number) => `/dashboard/school-configs/${id}`,
    },
    patrolSchedule: {
        list: () => '/dashboard/patrol-schedules',
        create: () => '/dashboard/patrol-schedules/create',
        edit: (id: number) => `/dashboard/patrol-schedules/${id}/edit`,
        detail: (id: number) => `/dashboard/patrol-schedules/${id}`,
    },
    studentSupervisor: {
        list: () => '/dashboard/student-supervisors',
        create: () => '/dashboard/student-supervisors/create',
        edit: (id: number) => `/dashboard/student-supervisors/${id}/edit`,
        detail: (id: number) => `/dashboard/student-supervisors/${id}`,
    },
    penalty: {
        list: () => '/dashboard/penalties',
        create: () => '/dashboard/penalties/create',
        edit: (id: number) => `/dashboard/penalties/${id}/edit`,
        detail: (id: number) => `/dashboard/penalties/${id}`,
    },
    registerSchool: {
        list: () => '/dashboard/registered-schools',
        create: () => '/dashboard/registered-schools/create',
        edit: (id: number) => `/dashboard/registered-schools/${id}/edit`,
        detail: (id: number) => `/dashboard/registered-schools/${id}`,
    },
    studentInClass: {
        list: () => '/dashboard/student-in-classes',
        create: () => '/dashboard/student-in-classes/create',
        edit: (id: number) => `/dashboard/student-in-classes/${id}/edit`,
        detail: (id: number) => `/dashboard/student-in-classes/${id}`,
        history: (id: number) => `/dashboard/student-in-classes/${id}/history`,
    },
    discipline: {
        list: () => '/dashboard/disciplines',
        create: () => '/dashboard/disciplines/create',
        edit: (id: number) => `/dashboard/disciplines/${id}/edit`,
        detail: (id: number) => `/dashboard/disciplines/${id}`,
        history: (id: number) => `/dashboard/disciplines/${id}/history`,
    },
    payment: {
        success: () => '/dashboard/payment/success',
        failure: () => '/dashboard/payment/failure',
    },
    order: {
        list: () => '/dashboard/order',
        create: () => '/dashboard/order',
        edit: (id: number) => `/dashboard/order/${id}`,
        detail: (id: number) => `/dashboard/order/${id}`,
    },
    semester: {
        list: () => '/dashboard/semester',
        create: () => '/dashboard/semester/create',
        edit: (id: number) => `/dashboard/semester/${id}/edit`,
        detail: (id: number) => `/dashboard/semester/${id}`,
    }
};
