import { Colors } from "../utils/colors.helper";
import { EnumListItem } from "./common";

export const MonthList: EnumListItem[] = [
    {
        value: 0,
        label: 'all',
        color: Colors.BLUE,
        id: 0,
        name: 'Tất cả',
        slug: 'all',
    },
    {
        value: 1,
        label: '1',
        color: Colors.BLUE,
        id: 1,
        name: '1',
        slug: '1',
    },
    {
        value: 2,
        label: '2',
        color: Colors.BLUE,
        id: 2,
        name: '2',
        slug: '2',
    },
    {
        value: 3,
        label: '3',
        color: Colors.BLUE,
        id: 3,
        name: '3',
        slug: '3',
    },
    {
        value: 4,
        label: '4',
        color: Colors.BLUE,
        id: 4,
        name: '4',
        slug: '4',
    },
    {
        value: 5,
        label: '5',
        color: Colors.BLUE,
        id: 5,
        name: '5',
        slug: '5',
    },
    {
        value: 6,
        label: '6',
        color: Colors.BLUE,
        id: 6,
        name: '6',
        slug: '6',
    },
    {
        value: 7,
        label: '7',
        color: Colors.BLUE,
        id: 7,
        name: '7',
        slug: '7',
    },
    {
        value: 8,
        label: '8',
        color: Colors.BLUE,
        id: 8,
        name: '8',
        slug: '8',
    },
    {
        value: 9,
        label: '9',
        color: Colors.BLUE,
        id: 9,
        name: '9',
        slug: '9',
    },
    {
        value: 10,
        label: '10',
        color: Colors.BLUE,
        id: 10,
        name: '10',
        slug: '10',
    },
    {
        value: 11,
        label: '11',
        color: Colors.BLUE,
        id: 11,
        name: '11',
        slug: '11',
    },
    {
        value: 12,
        label: '12',
        color: Colors.BLUE,
        id: 12,
        name: '12',
        slug: '12',
    },
];

export const WeekList: EnumListItem[] = [
    {
        value: 0,
        label: 'all',
        color: Colors.BLUE,
        id: 0,
        name: 'Tất cả',
        slug: 'all',
    },
    {
        value: 1,
        label: '1',
        color: Colors.BLUE,
        id: 1,
        name: '1',
        slug: '1',
    },
    {
        value: 2,
        label: '2',
        color: Colors.BLUE,
        id: 2,
        name: '2',
        slug: '2',
    },
    {
        value: 3,
        label: '3',
        color: Colors.BLUE,
        id: 3,
        name: '3',
        slug: '3',
    },
    {
        value: 4,
        label: '4',
        color: Colors.BLUE,
        id: 4,
        name: '4',
        slug: '4',
    },
];

export const SemesterList: EnumListItem[] = [
    {
        value: "",
        label: 'all',
        color: Colors.BLUE,
        id: "",
        name: 'Tất cả',
        slug: 'all',
    },
    {
        value: 'Học kỳ 1',
        label: 'Học kỳ 1',
        color: Colors.BLUE,
        id: 'Học kỳ 1',
        name: 'Học kỳ 1',
        slug: 'Học kỳ 1',
    },
    {
        value: 'Học kỳ 1',
        label: 'Học kỳ 2',
        color: Colors.BLUE,
        id: 'Học kỳ 2',
        name: 'Học kỳ 2',
        slug: 'Học kỳ 2',
    },
];