/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminLayoutImport } from './routes/_admin-layout'
import { Route as IndexImport } from './routes/index'
import { Route as PaymentSuccessImport } from './routes/payment/success'
import { Route as PaymentFailureImport } from './routes/payment/failure'
import { Route as AdminLayoutDashboardIndexImport } from './routes/_admin-layout.dashboard/index'
import { Route as AdminLayoutDashboardAnalyticsImport } from './routes/_admin-layout.dashboard/analytics'
import { Route as AdminLayoutDashboardIdImport } from './routes/_admin-layout.dashboard/$id'
import { Route as AdminLayoutDashboardYearPackagesIndexImport } from './routes/_admin-layout.dashboard/year-packages/index'
import { Route as AdminLayoutDashboardViolationsIndexImport } from './routes/_admin-layout.dashboard/violations/index'
import { Route as AdminLayoutDashboardViolationTypesIndexImport } from './routes/_admin-layout.dashboard/violation-types/index'
import { Route as AdminLayoutDashboardViolationGroupsIndexImport } from './routes/_admin-layout.dashboard/violation-groups/index'
import { Route as AdminLayoutDashboardViolationConfigsIndexImport } from './routes/_admin-layout.dashboard/violation-configs/index'
import { Route as AdminLayoutDashboardUserIndexImport } from './routes/_admin-layout.dashboard/user/index'
import { Route as AdminLayoutDashboardTimesIndexImport } from './routes/_admin-layout.dashboard/times/index'
import { Route as AdminLayoutDashboardTeachersIndexImport } from './routes/_admin-layout.dashboard/teachers/index'
import { Route as AdminLayoutDashboardStudentsIndexImport } from './routes/_admin-layout.dashboard/students/index'
import { Route as AdminLayoutDashboardStudentSupervisorsIndexImport } from './routes/_admin-layout.dashboard/student-supervisors/index'
import { Route as AdminLayoutDashboardStudentInClassesIndexImport } from './routes/_admin-layout.dashboard/student-in-classes/index'
import { Route as AdminLayoutDashboardSemesterIndexImport } from './routes/_admin-layout.dashboard/semester/index'
import { Route as AdminLayoutDashboardSchoolYearIndexImport } from './routes/_admin-layout.dashboard/school-year/index'
import { Route as AdminLayoutDashboardSchoolConfigsIndexImport } from './routes/_admin-layout.dashboard/school-configs/index'
import { Route as AdminLayoutDashboardSchoolAdminIndexImport } from './routes/_admin-layout.dashboard/school-admin/index'
import { Route as AdminLayoutDashboardRegisteredSchoolsIndexImport } from './routes/_admin-layout.dashboard/registered-schools/index'
import { Route as AdminLayoutDashboardPenaltiesIndexImport } from './routes/_admin-layout.dashboard/penalties/index'
import { Route as AdminLayoutDashboardPatrolSchedulesIndexImport } from './routes/_admin-layout.dashboard/patrol-schedules/index'
import { Route as AdminLayoutDashboardPackagesIndexImport } from './routes/_admin-layout.dashboard/packages/index'
import { Route as AdminLayoutDashboardOrderIndexImport } from './routes/_admin-layout.dashboard/order/index'
import { Route as AdminLayoutDashboardHighSchoolIndexImport } from './routes/_admin-layout.dashboard/high-school/index'
import { Route as AdminLayoutDashboardEvaluationsIndexImport } from './routes/_admin-layout.dashboard/evaluations/index'
import { Route as AdminLayoutDashboardEvaluationTopsIndexImport } from './routes/_admin-layout.dashboard/evaluation-tops/index'
import { Route as AdminLayoutDashboardEvaluationDetailsIndexImport } from './routes/_admin-layout.dashboard/evaluation-details/index'
import { Route as AdminLayoutDashboardDisciplinesIndexImport } from './routes/_admin-layout.dashboard/disciplines/index'
import { Route as AdminLayoutDashboardClassesIndexImport } from './routes/_admin-layout.dashboard/classes/index'
import { Route as AdminLayoutDashboardClassGroupIndexImport } from './routes/_admin-layout.dashboard/class-group/index'
import { Route as AdminLayoutDashboardViolationsCreateSupervisorImport } from './routes/_admin-layout.dashboard/violations/create-supervisor'
import { Route as AdminLayoutDashboardViolationsCreateStudentImport } from './routes/_admin-layout.dashboard/violations/create-student'
import { Route as AdminLayoutDashboardViolationTopsViolationTopStudentInClassImport } from './routes/_admin-layout.dashboard/violation-tops/violation-top-studentInClass'
import { Route as AdminLayoutDashboardViolationTopsViolationTopStudentImport } from './routes/_admin-layout.dashboard/violation-tops/violation-top-student'
import { Route as AdminLayoutDashboardViolationTopsViolationTopClassImport } from './routes/_admin-layout.dashboard/violation-tops/violation-top-class'
import { Route as AdminLayoutDashboardViolationTopsViolationInYearImport } from './routes/_admin-layout.dashboard/violation-tops/violation-in-year'
import { Route as AdminLayoutDashboardViolationTopsViolationInWeekImport } from './routes/_admin-layout.dashboard/violation-tops/violation-in-week'
import { Route as AdminLayoutDashboardViolationTopsViolationInClassImport } from './routes/_admin-layout.dashboard/violation-tops/violation-in-class'
import { Route as AdminLayoutDashboardViolationTopsViolationChartImport } from './routes/_admin-layout.dashboard/violation-tops/violation-chart'
import { Route as AdminLayoutDashboardPackagesBuyPackagesImport } from './routes/_admin-layout.dashboard/packages/buy-packages'
import { Route as AdminLayoutDashboardHighSchoolIdImport } from './routes/_admin-layout.dashboard/high-school/$id'
import { Route as AdminLayoutDashboardAuthViewImport } from './routes/_admin-layout.dashboard/auth/view'
import { Route as AdminLayoutDashboardAuthEditImport } from './routes/_admin-layout.dashboard/auth/edit'
import { Route as AdminLayoutDashboardViolationsIdIndexImport } from './routes/_admin-layout.dashboard/violations/$id/index'
import { Route as AdminLayoutDashboardDisciplinesIdIndexImport } from './routes/_admin-layout.dashboard/disciplines/$id/index'
import { Route as AdminLayoutDashboardClassesIdIndexImport } from './routes/_admin-layout.dashboard/classes/$id/index'
import { Route as AdminLayoutDashboardViolationsIdHistoryImport } from './routes/_admin-layout.dashboard/violations/$id/history'
import { Route as AdminLayoutDashboardViolationsIdEditImport } from './routes/_admin-layout.dashboard/violations/$id/edit'
import { Route as AdminLayoutDashboardStudentInClassesIdHistoryImport } from './routes/_admin-layout.dashboard/student-in-classes/$id/history'
import { Route as AdminLayoutDashboardDisciplinesIdHistoryImport } from './routes/_admin-layout.dashboard/disciplines/$id/history'
import { Route as AdminLayoutDashboardClassesIdHistoryImport } from './routes/_admin-layout.dashboard/classes/$id/history'

// Create/Update Routes

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/_admin-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PaymentSuccessRoute = PaymentSuccessImport.update({
  path: '/payment/success',
  getParentRoute: () => rootRoute,
} as any)

const PaymentFailureRoute = PaymentFailureImport.update({
  path: '/payment/failure',
  getParentRoute: () => rootRoute,
} as any)

const AdminLayoutDashboardIndexRoute = AdminLayoutDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutDashboardAnalyticsRoute =
  AdminLayoutDashboardAnalyticsImport.update({
    path: '/dashboard/analytics',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardIdRoute = AdminLayoutDashboardIdImport.update({
  path: '/dashboard/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutDashboardYearPackagesIndexRoute =
  AdminLayoutDashboardYearPackagesIndexImport.update({
    path: '/dashboard/year-packages/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationsIndexRoute =
  AdminLayoutDashboardViolationsIndexImport.update({
    path: '/dashboard/violations/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTypesIndexRoute =
  AdminLayoutDashboardViolationTypesIndexImport.update({
    path: '/dashboard/violation-types/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationGroupsIndexRoute =
  AdminLayoutDashboardViolationGroupsIndexImport.update({
    path: '/dashboard/violation-groups/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationConfigsIndexRoute =
  AdminLayoutDashboardViolationConfigsIndexImport.update({
    path: '/dashboard/violation-configs/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardUserIndexRoute =
  AdminLayoutDashboardUserIndexImport.update({
    path: '/dashboard/user/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardTimesIndexRoute =
  AdminLayoutDashboardTimesIndexImport.update({
    path: '/dashboard/times/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardTeachersIndexRoute =
  AdminLayoutDashboardTeachersIndexImport.update({
    path: '/dashboard/teachers/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardStudentsIndexRoute =
  AdminLayoutDashboardStudentsIndexImport.update({
    path: '/dashboard/students/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardStudentSupervisorsIndexRoute =
  AdminLayoutDashboardStudentSupervisorsIndexImport.update({
    path: '/dashboard/student-supervisors/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardStudentInClassesIndexRoute =
  AdminLayoutDashboardStudentInClassesIndexImport.update({
    path: '/dashboard/student-in-classes/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardSemesterIndexRoute =
  AdminLayoutDashboardSemesterIndexImport.update({
    path: '/dashboard/semester/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardSchoolYearIndexRoute =
  AdminLayoutDashboardSchoolYearIndexImport.update({
    path: '/dashboard/school-year/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardSchoolConfigsIndexRoute =
  AdminLayoutDashboardSchoolConfigsIndexImport.update({
    path: '/dashboard/school-configs/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardSchoolAdminIndexRoute =
  AdminLayoutDashboardSchoolAdminIndexImport.update({
    path: '/dashboard/school-admin/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardRegisteredSchoolsIndexRoute =
  AdminLayoutDashboardRegisteredSchoolsIndexImport.update({
    path: '/dashboard/registered-schools/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardPenaltiesIndexRoute =
  AdminLayoutDashboardPenaltiesIndexImport.update({
    path: '/dashboard/penalties/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardPatrolSchedulesIndexRoute =
  AdminLayoutDashboardPatrolSchedulesIndexImport.update({
    path: '/dashboard/patrol-schedules/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardPackagesIndexRoute =
  AdminLayoutDashboardPackagesIndexImport.update({
    path: '/dashboard/packages/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardOrderIndexRoute =
  AdminLayoutDashboardOrderIndexImport.update({
    path: '/dashboard/order/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardHighSchoolIndexRoute =
  AdminLayoutDashboardHighSchoolIndexImport.update({
    path: '/dashboard/high-school/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardEvaluationsIndexRoute =
  AdminLayoutDashboardEvaluationsIndexImport.update({
    path: '/dashboard/evaluations/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardEvaluationTopsIndexRoute =
  AdminLayoutDashboardEvaluationTopsIndexImport.update({
    path: '/dashboard/evaluation-tops/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardEvaluationDetailsIndexRoute =
  AdminLayoutDashboardEvaluationDetailsIndexImport.update({
    path: '/dashboard/evaluation-details/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardDisciplinesIndexRoute =
  AdminLayoutDashboardDisciplinesIndexImport.update({
    path: '/dashboard/disciplines/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardClassesIndexRoute =
  AdminLayoutDashboardClassesIndexImport.update({
    path: '/dashboard/classes/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardClassGroupIndexRoute =
  AdminLayoutDashboardClassGroupIndexImport.update({
    path: '/dashboard/class-group/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationsCreateSupervisorRoute =
  AdminLayoutDashboardViolationsCreateSupervisorImport.update({
    path: '/dashboard/violations/create-supervisor',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationsCreateStudentRoute =
  AdminLayoutDashboardViolationsCreateStudentImport.update({
    path: '/dashboard/violations/create-student',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute =
  AdminLayoutDashboardViolationTopsViolationTopStudentInClassImport.update({
    path: '/dashboard/violation-tops/violation-top-studentInClass',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationTopStudentRoute =
  AdminLayoutDashboardViolationTopsViolationTopStudentImport.update({
    path: '/dashboard/violation-tops/violation-top-student',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationTopClassRoute =
  AdminLayoutDashboardViolationTopsViolationTopClassImport.update({
    path: '/dashboard/violation-tops/violation-top-class',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationInYearRoute =
  AdminLayoutDashboardViolationTopsViolationInYearImport.update({
    path: '/dashboard/violation-tops/violation-in-year',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationInWeekRoute =
  AdminLayoutDashboardViolationTopsViolationInWeekImport.update({
    path: '/dashboard/violation-tops/violation-in-week',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationInClassRoute =
  AdminLayoutDashboardViolationTopsViolationInClassImport.update({
    path: '/dashboard/violation-tops/violation-in-class',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationTopsViolationChartRoute =
  AdminLayoutDashboardViolationTopsViolationChartImport.update({
    path: '/dashboard/violation-tops/violation-chart',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardPackagesBuyPackagesRoute =
  AdminLayoutDashboardPackagesBuyPackagesImport.update({
    path: '/dashboard/packages/buy-packages',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardHighSchoolIdRoute =
  AdminLayoutDashboardHighSchoolIdImport.update({
    path: '/dashboard/high-school/$id',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardAuthViewRoute =
  AdminLayoutDashboardAuthViewImport.update({
    path: '/dashboard/auth/view',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardAuthEditRoute =
  AdminLayoutDashboardAuthEditImport.update({
    path: '/dashboard/auth/edit',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationsIdIndexRoute =
  AdminLayoutDashboardViolationsIdIndexImport.update({
    path: '/dashboard/violations/$id/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardDisciplinesIdIndexRoute =
  AdminLayoutDashboardDisciplinesIdIndexImport.update({
    path: '/dashboard/disciplines/$id/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardClassesIdIndexRoute =
  AdminLayoutDashboardClassesIdIndexImport.update({
    path: '/dashboard/classes/$id/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationsIdHistoryRoute =
  AdminLayoutDashboardViolationsIdHistoryImport.update({
    path: '/dashboard/violations/$id/history',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardViolationsIdEditRoute =
  AdminLayoutDashboardViolationsIdEditImport.update({
    path: '/dashboard/violations/$id/edit',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardStudentInClassesIdHistoryRoute =
  AdminLayoutDashboardStudentInClassesIdHistoryImport.update({
    path: '/dashboard/student-in-classes/$id/history',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardDisciplinesIdHistoryRoute =
  AdminLayoutDashboardDisciplinesIdHistoryImport.update({
    path: '/dashboard/disciplines/$id/history',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutDashboardClassesIdHistoryRoute =
  AdminLayoutDashboardClassesIdHistoryImport.update({
    path: '/dashboard/classes/$id/history',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_admin-layout': {
      id: '/_admin-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof rootRoute
    }
    '/payment/failure': {
      id: '/payment/failure'
      path: '/payment/failure'
      fullPath: '/payment/failure'
      preLoaderRoute: typeof PaymentFailureImport
      parentRoute: typeof rootRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessImport
      parentRoute: typeof rootRoute
    }
    '/_admin-layout/dashboard/$id': {
      id: '/_admin-layout/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof AdminLayoutDashboardIdImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/analytics': {
      id: '/_admin-layout/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AdminLayoutDashboardAnalyticsImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/': {
      id: '/_admin-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/auth/edit': {
      id: '/_admin-layout/dashboard/auth/edit'
      path: '/dashboard/auth/edit'
      fullPath: '/dashboard/auth/edit'
      preLoaderRoute: typeof AdminLayoutDashboardAuthEditImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/auth/view': {
      id: '/_admin-layout/dashboard/auth/view'
      path: '/dashboard/auth/view'
      fullPath: '/dashboard/auth/view'
      preLoaderRoute: typeof AdminLayoutDashboardAuthViewImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/high-school/$id': {
      id: '/_admin-layout/dashboard/high-school/$id'
      path: '/dashboard/high-school/$id'
      fullPath: '/dashboard/high-school/$id'
      preLoaderRoute: typeof AdminLayoutDashboardHighSchoolIdImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/packages/buy-packages': {
      id: '/_admin-layout/dashboard/packages/buy-packages'
      path: '/dashboard/packages/buy-packages'
      fullPath: '/dashboard/packages/buy-packages'
      preLoaderRoute: typeof AdminLayoutDashboardPackagesBuyPackagesImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-chart': {
      id: '/_admin-layout/dashboard/violation-tops/violation-chart'
      path: '/dashboard/violation-tops/violation-chart'
      fullPath: '/dashboard/violation-tops/violation-chart'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationChartImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-in-class': {
      id: '/_admin-layout/dashboard/violation-tops/violation-in-class'
      path: '/dashboard/violation-tops/violation-in-class'
      fullPath: '/dashboard/violation-tops/violation-in-class'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationInClassImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-in-week': {
      id: '/_admin-layout/dashboard/violation-tops/violation-in-week'
      path: '/dashboard/violation-tops/violation-in-week'
      fullPath: '/dashboard/violation-tops/violation-in-week'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationInWeekImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-in-year': {
      id: '/_admin-layout/dashboard/violation-tops/violation-in-year'
      path: '/dashboard/violation-tops/violation-in-year'
      fullPath: '/dashboard/violation-tops/violation-in-year'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationInYearImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-top-class': {
      id: '/_admin-layout/dashboard/violation-tops/violation-top-class'
      path: '/dashboard/violation-tops/violation-top-class'
      fullPath: '/dashboard/violation-tops/violation-top-class'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationTopClassImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-top-student': {
      id: '/_admin-layout/dashboard/violation-tops/violation-top-student'
      path: '/dashboard/violation-tops/violation-top-student'
      fullPath: '/dashboard/violation-tops/violation-top-student'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationTopStudentImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-tops/violation-top-studentInClass': {
      id: '/_admin-layout/dashboard/violation-tops/violation-top-studentInClass'
      path: '/dashboard/violation-tops/violation-top-studentInClass'
      fullPath: '/dashboard/violation-tops/violation-top-studentInClass'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTopsViolationTopStudentInClassImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violations/create-student': {
      id: '/_admin-layout/dashboard/violations/create-student'
      path: '/dashboard/violations/create-student'
      fullPath: '/dashboard/violations/create-student'
      preLoaderRoute: typeof AdminLayoutDashboardViolationsCreateStudentImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violations/create-supervisor': {
      id: '/_admin-layout/dashboard/violations/create-supervisor'
      path: '/dashboard/violations/create-supervisor'
      fullPath: '/dashboard/violations/create-supervisor'
      preLoaderRoute: typeof AdminLayoutDashboardViolationsCreateSupervisorImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/class-group/': {
      id: '/_admin-layout/dashboard/class-group/'
      path: '/dashboard/class-group'
      fullPath: '/dashboard/class-group'
      preLoaderRoute: typeof AdminLayoutDashboardClassGroupIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/classes/': {
      id: '/_admin-layout/dashboard/classes/'
      path: '/dashboard/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof AdminLayoutDashboardClassesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/disciplines/': {
      id: '/_admin-layout/dashboard/disciplines/'
      path: '/dashboard/disciplines'
      fullPath: '/dashboard/disciplines'
      preLoaderRoute: typeof AdminLayoutDashboardDisciplinesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/evaluation-details/': {
      id: '/_admin-layout/dashboard/evaluation-details/'
      path: '/dashboard/evaluation-details'
      fullPath: '/dashboard/evaluation-details'
      preLoaderRoute: typeof AdminLayoutDashboardEvaluationDetailsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/evaluation-tops/': {
      id: '/_admin-layout/dashboard/evaluation-tops/'
      path: '/dashboard/evaluation-tops'
      fullPath: '/dashboard/evaluation-tops'
      preLoaderRoute: typeof AdminLayoutDashboardEvaluationTopsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/evaluations/': {
      id: '/_admin-layout/dashboard/evaluations/'
      path: '/dashboard/evaluations'
      fullPath: '/dashboard/evaluations'
      preLoaderRoute: typeof AdminLayoutDashboardEvaluationsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/high-school/': {
      id: '/_admin-layout/dashboard/high-school/'
      path: '/dashboard/high-school'
      fullPath: '/dashboard/high-school'
      preLoaderRoute: typeof AdminLayoutDashboardHighSchoolIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/order/': {
      id: '/_admin-layout/dashboard/order/'
      path: '/dashboard/order'
      fullPath: '/dashboard/order'
      preLoaderRoute: typeof AdminLayoutDashboardOrderIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/packages/': {
      id: '/_admin-layout/dashboard/packages/'
      path: '/dashboard/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof AdminLayoutDashboardPackagesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/patrol-schedules/': {
      id: '/_admin-layout/dashboard/patrol-schedules/'
      path: '/dashboard/patrol-schedules'
      fullPath: '/dashboard/patrol-schedules'
      preLoaderRoute: typeof AdminLayoutDashboardPatrolSchedulesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/penalties/': {
      id: '/_admin-layout/dashboard/penalties/'
      path: '/dashboard/penalties'
      fullPath: '/dashboard/penalties'
      preLoaderRoute: typeof AdminLayoutDashboardPenaltiesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/registered-schools/': {
      id: '/_admin-layout/dashboard/registered-schools/'
      path: '/dashboard/registered-schools'
      fullPath: '/dashboard/registered-schools'
      preLoaderRoute: typeof AdminLayoutDashboardRegisteredSchoolsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/school-admin/': {
      id: '/_admin-layout/dashboard/school-admin/'
      path: '/dashboard/school-admin'
      fullPath: '/dashboard/school-admin'
      preLoaderRoute: typeof AdminLayoutDashboardSchoolAdminIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/school-configs/': {
      id: '/_admin-layout/dashboard/school-configs/'
      path: '/dashboard/school-configs'
      fullPath: '/dashboard/school-configs'
      preLoaderRoute: typeof AdminLayoutDashboardSchoolConfigsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/school-year/': {
      id: '/_admin-layout/dashboard/school-year/'
      path: '/dashboard/school-year'
      fullPath: '/dashboard/school-year'
      preLoaderRoute: typeof AdminLayoutDashboardSchoolYearIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/semester/': {
      id: '/_admin-layout/dashboard/semester/'
      path: '/dashboard/semester'
      fullPath: '/dashboard/semester'
      preLoaderRoute: typeof AdminLayoutDashboardSemesterIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/student-in-classes/': {
      id: '/_admin-layout/dashboard/student-in-classes/'
      path: '/dashboard/student-in-classes'
      fullPath: '/dashboard/student-in-classes'
      preLoaderRoute: typeof AdminLayoutDashboardStudentInClassesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/student-supervisors/': {
      id: '/_admin-layout/dashboard/student-supervisors/'
      path: '/dashboard/student-supervisors'
      fullPath: '/dashboard/student-supervisors'
      preLoaderRoute: typeof AdminLayoutDashboardStudentSupervisorsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/students/': {
      id: '/_admin-layout/dashboard/students/'
      path: '/dashboard/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof AdminLayoutDashboardStudentsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/teachers/': {
      id: '/_admin-layout/dashboard/teachers/'
      path: '/dashboard/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof AdminLayoutDashboardTeachersIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/times/': {
      id: '/_admin-layout/dashboard/times/'
      path: '/dashboard/times'
      fullPath: '/dashboard/times'
      preLoaderRoute: typeof AdminLayoutDashboardTimesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/user/': {
      id: '/_admin-layout/dashboard/user/'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof AdminLayoutDashboardUserIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-configs/': {
      id: '/_admin-layout/dashboard/violation-configs/'
      path: '/dashboard/violation-configs'
      fullPath: '/dashboard/violation-configs'
      preLoaderRoute: typeof AdminLayoutDashboardViolationConfigsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-groups/': {
      id: '/_admin-layout/dashboard/violation-groups/'
      path: '/dashboard/violation-groups'
      fullPath: '/dashboard/violation-groups'
      preLoaderRoute: typeof AdminLayoutDashboardViolationGroupsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violation-types/': {
      id: '/_admin-layout/dashboard/violation-types/'
      path: '/dashboard/violation-types'
      fullPath: '/dashboard/violation-types'
      preLoaderRoute: typeof AdminLayoutDashboardViolationTypesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violations/': {
      id: '/_admin-layout/dashboard/violations/'
      path: '/dashboard/violations'
      fullPath: '/dashboard/violations'
      preLoaderRoute: typeof AdminLayoutDashboardViolationsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/year-packages/': {
      id: '/_admin-layout/dashboard/year-packages/'
      path: '/dashboard/year-packages'
      fullPath: '/dashboard/year-packages'
      preLoaderRoute: typeof AdminLayoutDashboardYearPackagesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/classes/$id/history': {
      id: '/_admin-layout/dashboard/classes/$id/history'
      path: '/dashboard/classes/$id/history'
      fullPath: '/dashboard/classes/$id/history'
      preLoaderRoute: typeof AdminLayoutDashboardClassesIdHistoryImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/disciplines/$id/history': {
      id: '/_admin-layout/dashboard/disciplines/$id/history'
      path: '/dashboard/disciplines/$id/history'
      fullPath: '/dashboard/disciplines/$id/history'
      preLoaderRoute: typeof AdminLayoutDashboardDisciplinesIdHistoryImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/student-in-classes/$id/history': {
      id: '/_admin-layout/dashboard/student-in-classes/$id/history'
      path: '/dashboard/student-in-classes/$id/history'
      fullPath: '/dashboard/student-in-classes/$id/history'
      preLoaderRoute: typeof AdminLayoutDashboardStudentInClassesIdHistoryImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violations/$id/edit': {
      id: '/_admin-layout/dashboard/violations/$id/edit'
      path: '/dashboard/violations/$id/edit'
      fullPath: '/dashboard/violations/$id/edit'
      preLoaderRoute: typeof AdminLayoutDashboardViolationsIdEditImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violations/$id/history': {
      id: '/_admin-layout/dashboard/violations/$id/history'
      path: '/dashboard/violations/$id/history'
      fullPath: '/dashboard/violations/$id/history'
      preLoaderRoute: typeof AdminLayoutDashboardViolationsIdHistoryImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/classes/$id/': {
      id: '/_admin-layout/dashboard/classes/$id/'
      path: '/dashboard/classes/$id'
      fullPath: '/dashboard/classes/$id'
      preLoaderRoute: typeof AdminLayoutDashboardClassesIdIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/disciplines/$id/': {
      id: '/_admin-layout/dashboard/disciplines/$id/'
      path: '/dashboard/disciplines/$id'
      fullPath: '/dashboard/disciplines/$id'
      preLoaderRoute: typeof AdminLayoutDashboardDisciplinesIdIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin-layout/dashboard/violations/$id/': {
      id: '/_admin-layout/dashboard/violations/$id/'
      path: '/dashboard/violations/$id'
      fullPath: '/dashboard/violations/$id'
      preLoaderRoute: typeof AdminLayoutDashboardViolationsIdIndexImport
      parentRoute: typeof AdminLayoutImport
    }
  }
}

// Create and export the route tree

interface AdminLayoutRouteChildren {
  AdminLayoutDashboardIdRoute: typeof AdminLayoutDashboardIdRoute
  AdminLayoutDashboardAnalyticsRoute: typeof AdminLayoutDashboardAnalyticsRoute
  AdminLayoutDashboardIndexRoute: typeof AdminLayoutDashboardIndexRoute
  AdminLayoutDashboardAuthEditRoute: typeof AdminLayoutDashboardAuthEditRoute
  AdminLayoutDashboardAuthViewRoute: typeof AdminLayoutDashboardAuthViewRoute
  AdminLayoutDashboardHighSchoolIdRoute: typeof AdminLayoutDashboardHighSchoolIdRoute
  AdminLayoutDashboardPackagesBuyPackagesRoute: typeof AdminLayoutDashboardPackagesBuyPackagesRoute
  AdminLayoutDashboardViolationTopsViolationChartRoute: typeof AdminLayoutDashboardViolationTopsViolationChartRoute
  AdminLayoutDashboardViolationTopsViolationInClassRoute: typeof AdminLayoutDashboardViolationTopsViolationInClassRoute
  AdminLayoutDashboardViolationTopsViolationInWeekRoute: typeof AdminLayoutDashboardViolationTopsViolationInWeekRoute
  AdminLayoutDashboardViolationTopsViolationInYearRoute: typeof AdminLayoutDashboardViolationTopsViolationInYearRoute
  AdminLayoutDashboardViolationTopsViolationTopClassRoute: typeof AdminLayoutDashboardViolationTopsViolationTopClassRoute
  AdminLayoutDashboardViolationTopsViolationTopStudentRoute: typeof AdminLayoutDashboardViolationTopsViolationTopStudentRoute
  AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute: typeof AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute
  AdminLayoutDashboardViolationsCreateStudentRoute: typeof AdminLayoutDashboardViolationsCreateStudentRoute
  AdminLayoutDashboardViolationsCreateSupervisorRoute: typeof AdminLayoutDashboardViolationsCreateSupervisorRoute
  AdminLayoutDashboardClassGroupIndexRoute: typeof AdminLayoutDashboardClassGroupIndexRoute
  AdminLayoutDashboardClassesIndexRoute: typeof AdminLayoutDashboardClassesIndexRoute
  AdminLayoutDashboardDisciplinesIndexRoute: typeof AdminLayoutDashboardDisciplinesIndexRoute
  AdminLayoutDashboardEvaluationDetailsIndexRoute: typeof AdminLayoutDashboardEvaluationDetailsIndexRoute
  AdminLayoutDashboardEvaluationTopsIndexRoute: typeof AdminLayoutDashboardEvaluationTopsIndexRoute
  AdminLayoutDashboardEvaluationsIndexRoute: typeof AdminLayoutDashboardEvaluationsIndexRoute
  AdminLayoutDashboardHighSchoolIndexRoute: typeof AdminLayoutDashboardHighSchoolIndexRoute
  AdminLayoutDashboardOrderIndexRoute: typeof AdminLayoutDashboardOrderIndexRoute
  AdminLayoutDashboardPackagesIndexRoute: typeof AdminLayoutDashboardPackagesIndexRoute
  AdminLayoutDashboardPatrolSchedulesIndexRoute: typeof AdminLayoutDashboardPatrolSchedulesIndexRoute
  AdminLayoutDashboardPenaltiesIndexRoute: typeof AdminLayoutDashboardPenaltiesIndexRoute
  AdminLayoutDashboardRegisteredSchoolsIndexRoute: typeof AdminLayoutDashboardRegisteredSchoolsIndexRoute
  AdminLayoutDashboardSchoolAdminIndexRoute: typeof AdminLayoutDashboardSchoolAdminIndexRoute
  AdminLayoutDashboardSchoolConfigsIndexRoute: typeof AdminLayoutDashboardSchoolConfigsIndexRoute
  AdminLayoutDashboardSchoolYearIndexRoute: typeof AdminLayoutDashboardSchoolYearIndexRoute
  AdminLayoutDashboardSemesterIndexRoute: typeof AdminLayoutDashboardSemesterIndexRoute
  AdminLayoutDashboardStudentInClassesIndexRoute: typeof AdminLayoutDashboardStudentInClassesIndexRoute
  AdminLayoutDashboardStudentSupervisorsIndexRoute: typeof AdminLayoutDashboardStudentSupervisorsIndexRoute
  AdminLayoutDashboardStudentsIndexRoute: typeof AdminLayoutDashboardStudentsIndexRoute
  AdminLayoutDashboardTeachersIndexRoute: typeof AdminLayoutDashboardTeachersIndexRoute
  AdminLayoutDashboardTimesIndexRoute: typeof AdminLayoutDashboardTimesIndexRoute
  AdminLayoutDashboardUserIndexRoute: typeof AdminLayoutDashboardUserIndexRoute
  AdminLayoutDashboardViolationConfigsIndexRoute: typeof AdminLayoutDashboardViolationConfigsIndexRoute
  AdminLayoutDashboardViolationGroupsIndexRoute: typeof AdminLayoutDashboardViolationGroupsIndexRoute
  AdminLayoutDashboardViolationTypesIndexRoute: typeof AdminLayoutDashboardViolationTypesIndexRoute
  AdminLayoutDashboardViolationsIndexRoute: typeof AdminLayoutDashboardViolationsIndexRoute
  AdminLayoutDashboardYearPackagesIndexRoute: typeof AdminLayoutDashboardYearPackagesIndexRoute
  AdminLayoutDashboardClassesIdHistoryRoute: typeof AdminLayoutDashboardClassesIdHistoryRoute
  AdminLayoutDashboardDisciplinesIdHistoryRoute: typeof AdminLayoutDashboardDisciplinesIdHistoryRoute
  AdminLayoutDashboardStudentInClassesIdHistoryRoute: typeof AdminLayoutDashboardStudentInClassesIdHistoryRoute
  AdminLayoutDashboardViolationsIdEditRoute: typeof AdminLayoutDashboardViolationsIdEditRoute
  AdminLayoutDashboardViolationsIdHistoryRoute: typeof AdminLayoutDashboardViolationsIdHistoryRoute
  AdminLayoutDashboardClassesIdIndexRoute: typeof AdminLayoutDashboardClassesIdIndexRoute
  AdminLayoutDashboardDisciplinesIdIndexRoute: typeof AdminLayoutDashboardDisciplinesIdIndexRoute
  AdminLayoutDashboardViolationsIdIndexRoute: typeof AdminLayoutDashboardViolationsIdIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDashboardIdRoute: AdminLayoutDashboardIdRoute,
  AdminLayoutDashboardAnalyticsRoute: AdminLayoutDashboardAnalyticsRoute,
  AdminLayoutDashboardIndexRoute: AdminLayoutDashboardIndexRoute,
  AdminLayoutDashboardAuthEditRoute: AdminLayoutDashboardAuthEditRoute,
  AdminLayoutDashboardAuthViewRoute: AdminLayoutDashboardAuthViewRoute,
  AdminLayoutDashboardHighSchoolIdRoute: AdminLayoutDashboardHighSchoolIdRoute,
  AdminLayoutDashboardPackagesBuyPackagesRoute:
    AdminLayoutDashboardPackagesBuyPackagesRoute,
  AdminLayoutDashboardViolationTopsViolationChartRoute:
    AdminLayoutDashboardViolationTopsViolationChartRoute,
  AdminLayoutDashboardViolationTopsViolationInClassRoute:
    AdminLayoutDashboardViolationTopsViolationInClassRoute,
  AdminLayoutDashboardViolationTopsViolationInWeekRoute:
    AdminLayoutDashboardViolationTopsViolationInWeekRoute,
  AdminLayoutDashboardViolationTopsViolationInYearRoute:
    AdminLayoutDashboardViolationTopsViolationInYearRoute,
  AdminLayoutDashboardViolationTopsViolationTopClassRoute:
    AdminLayoutDashboardViolationTopsViolationTopClassRoute,
  AdminLayoutDashboardViolationTopsViolationTopStudentRoute:
    AdminLayoutDashboardViolationTopsViolationTopStudentRoute,
  AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute:
    AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute,
  AdminLayoutDashboardViolationsCreateStudentRoute:
    AdminLayoutDashboardViolationsCreateStudentRoute,
  AdminLayoutDashboardViolationsCreateSupervisorRoute:
    AdminLayoutDashboardViolationsCreateSupervisorRoute,
  AdminLayoutDashboardClassGroupIndexRoute:
    AdminLayoutDashboardClassGroupIndexRoute,
  AdminLayoutDashboardClassesIndexRoute: AdminLayoutDashboardClassesIndexRoute,
  AdminLayoutDashboardDisciplinesIndexRoute:
    AdminLayoutDashboardDisciplinesIndexRoute,
  AdminLayoutDashboardEvaluationDetailsIndexRoute:
    AdminLayoutDashboardEvaluationDetailsIndexRoute,
  AdminLayoutDashboardEvaluationTopsIndexRoute:
    AdminLayoutDashboardEvaluationTopsIndexRoute,
  AdminLayoutDashboardEvaluationsIndexRoute:
    AdminLayoutDashboardEvaluationsIndexRoute,
  AdminLayoutDashboardHighSchoolIndexRoute:
    AdminLayoutDashboardHighSchoolIndexRoute,
  AdminLayoutDashboardOrderIndexRoute: AdminLayoutDashboardOrderIndexRoute,
  AdminLayoutDashboardPackagesIndexRoute:
    AdminLayoutDashboardPackagesIndexRoute,
  AdminLayoutDashboardPatrolSchedulesIndexRoute:
    AdminLayoutDashboardPatrolSchedulesIndexRoute,
  AdminLayoutDashboardPenaltiesIndexRoute:
    AdminLayoutDashboardPenaltiesIndexRoute,
  AdminLayoutDashboardRegisteredSchoolsIndexRoute:
    AdminLayoutDashboardRegisteredSchoolsIndexRoute,
  AdminLayoutDashboardSchoolAdminIndexRoute:
    AdminLayoutDashboardSchoolAdminIndexRoute,
  AdminLayoutDashboardSchoolConfigsIndexRoute:
    AdminLayoutDashboardSchoolConfigsIndexRoute,
  AdminLayoutDashboardSchoolYearIndexRoute:
    AdminLayoutDashboardSchoolYearIndexRoute,
  AdminLayoutDashboardSemesterIndexRoute:
    AdminLayoutDashboardSemesterIndexRoute,
  AdminLayoutDashboardStudentInClassesIndexRoute:
    AdminLayoutDashboardStudentInClassesIndexRoute,
  AdminLayoutDashboardStudentSupervisorsIndexRoute:
    AdminLayoutDashboardStudentSupervisorsIndexRoute,
  AdminLayoutDashboardStudentsIndexRoute:
    AdminLayoutDashboardStudentsIndexRoute,
  AdminLayoutDashboardTeachersIndexRoute:
    AdminLayoutDashboardTeachersIndexRoute,
  AdminLayoutDashboardTimesIndexRoute: AdminLayoutDashboardTimesIndexRoute,
  AdminLayoutDashboardUserIndexRoute: AdminLayoutDashboardUserIndexRoute,
  AdminLayoutDashboardViolationConfigsIndexRoute:
    AdminLayoutDashboardViolationConfigsIndexRoute,
  AdminLayoutDashboardViolationGroupsIndexRoute:
    AdminLayoutDashboardViolationGroupsIndexRoute,
  AdminLayoutDashboardViolationTypesIndexRoute:
    AdminLayoutDashboardViolationTypesIndexRoute,
  AdminLayoutDashboardViolationsIndexRoute:
    AdminLayoutDashboardViolationsIndexRoute,
  AdminLayoutDashboardYearPackagesIndexRoute:
    AdminLayoutDashboardYearPackagesIndexRoute,
  AdminLayoutDashboardClassesIdHistoryRoute:
    AdminLayoutDashboardClassesIdHistoryRoute,
  AdminLayoutDashboardDisciplinesIdHistoryRoute:
    AdminLayoutDashboardDisciplinesIdHistoryRoute,
  AdminLayoutDashboardStudentInClassesIdHistoryRoute:
    AdminLayoutDashboardStudentInClassesIdHistoryRoute,
  AdminLayoutDashboardViolationsIdEditRoute:
    AdminLayoutDashboardViolationsIdEditRoute,
  AdminLayoutDashboardViolationsIdHistoryRoute:
    AdminLayoutDashboardViolationsIdHistoryRoute,
  AdminLayoutDashboardClassesIdIndexRoute:
    AdminLayoutDashboardClassesIdIndexRoute,
  AdminLayoutDashboardDisciplinesIdIndexRoute:
    AdminLayoutDashboardDisciplinesIdIndexRoute,
  AdminLayoutDashboardViolationsIdIndexRoute:
    AdminLayoutDashboardViolationsIdIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AdminLayoutRouteWithChildren
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/dashboard/$id': typeof AdminLayoutDashboardIdRoute
  '/dashboard/analytics': typeof AdminLayoutDashboardAnalyticsRoute
  '/dashboard': typeof AdminLayoutDashboardIndexRoute
  '/dashboard/auth/edit': typeof AdminLayoutDashboardAuthEditRoute
  '/dashboard/auth/view': typeof AdminLayoutDashboardAuthViewRoute
  '/dashboard/high-school/$id': typeof AdminLayoutDashboardHighSchoolIdRoute
  '/dashboard/packages/buy-packages': typeof AdminLayoutDashboardPackagesBuyPackagesRoute
  '/dashboard/violation-tops/violation-chart': typeof AdminLayoutDashboardViolationTopsViolationChartRoute
  '/dashboard/violation-tops/violation-in-class': typeof AdminLayoutDashboardViolationTopsViolationInClassRoute
  '/dashboard/violation-tops/violation-in-week': typeof AdminLayoutDashboardViolationTopsViolationInWeekRoute
  '/dashboard/violation-tops/violation-in-year': typeof AdminLayoutDashboardViolationTopsViolationInYearRoute
  '/dashboard/violation-tops/violation-top-class': typeof AdminLayoutDashboardViolationTopsViolationTopClassRoute
  '/dashboard/violation-tops/violation-top-student': typeof AdminLayoutDashboardViolationTopsViolationTopStudentRoute
  '/dashboard/violation-tops/violation-top-studentInClass': typeof AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute
  '/dashboard/violations/create-student': typeof AdminLayoutDashboardViolationsCreateStudentRoute
  '/dashboard/violations/create-supervisor': typeof AdminLayoutDashboardViolationsCreateSupervisorRoute
  '/dashboard/class-group': typeof AdminLayoutDashboardClassGroupIndexRoute
  '/dashboard/classes': typeof AdminLayoutDashboardClassesIndexRoute
  '/dashboard/disciplines': typeof AdminLayoutDashboardDisciplinesIndexRoute
  '/dashboard/evaluation-details': typeof AdminLayoutDashboardEvaluationDetailsIndexRoute
  '/dashboard/evaluation-tops': typeof AdminLayoutDashboardEvaluationTopsIndexRoute
  '/dashboard/evaluations': typeof AdminLayoutDashboardEvaluationsIndexRoute
  '/dashboard/high-school': typeof AdminLayoutDashboardHighSchoolIndexRoute
  '/dashboard/order': typeof AdminLayoutDashboardOrderIndexRoute
  '/dashboard/packages': typeof AdminLayoutDashboardPackagesIndexRoute
  '/dashboard/patrol-schedules': typeof AdminLayoutDashboardPatrolSchedulesIndexRoute
  '/dashboard/penalties': typeof AdminLayoutDashboardPenaltiesIndexRoute
  '/dashboard/registered-schools': typeof AdminLayoutDashboardRegisteredSchoolsIndexRoute
  '/dashboard/school-admin': typeof AdminLayoutDashboardSchoolAdminIndexRoute
  '/dashboard/school-configs': typeof AdminLayoutDashboardSchoolConfigsIndexRoute
  '/dashboard/school-year': typeof AdminLayoutDashboardSchoolYearIndexRoute
  '/dashboard/semester': typeof AdminLayoutDashboardSemesterIndexRoute
  '/dashboard/student-in-classes': typeof AdminLayoutDashboardStudentInClassesIndexRoute
  '/dashboard/student-supervisors': typeof AdminLayoutDashboardStudentSupervisorsIndexRoute
  '/dashboard/students': typeof AdminLayoutDashboardStudentsIndexRoute
  '/dashboard/teachers': typeof AdminLayoutDashboardTeachersIndexRoute
  '/dashboard/times': typeof AdminLayoutDashboardTimesIndexRoute
  '/dashboard/user': typeof AdminLayoutDashboardUserIndexRoute
  '/dashboard/violation-configs': typeof AdminLayoutDashboardViolationConfigsIndexRoute
  '/dashboard/violation-groups': typeof AdminLayoutDashboardViolationGroupsIndexRoute
  '/dashboard/violation-types': typeof AdminLayoutDashboardViolationTypesIndexRoute
  '/dashboard/violations': typeof AdminLayoutDashboardViolationsIndexRoute
  '/dashboard/year-packages': typeof AdminLayoutDashboardYearPackagesIndexRoute
  '/dashboard/classes/$id/history': typeof AdminLayoutDashboardClassesIdHistoryRoute
  '/dashboard/disciplines/$id/history': typeof AdminLayoutDashboardDisciplinesIdHistoryRoute
  '/dashboard/student-in-classes/$id/history': typeof AdminLayoutDashboardStudentInClassesIdHistoryRoute
  '/dashboard/violations/$id/edit': typeof AdminLayoutDashboardViolationsIdEditRoute
  '/dashboard/violations/$id/history': typeof AdminLayoutDashboardViolationsIdHistoryRoute
  '/dashboard/classes/$id': typeof AdminLayoutDashboardClassesIdIndexRoute
  '/dashboard/disciplines/$id': typeof AdminLayoutDashboardDisciplinesIdIndexRoute
  '/dashboard/violations/$id': typeof AdminLayoutDashboardViolationsIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AdminLayoutRouteWithChildren
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/dashboard/$id': typeof AdminLayoutDashboardIdRoute
  '/dashboard/analytics': typeof AdminLayoutDashboardAnalyticsRoute
  '/dashboard': typeof AdminLayoutDashboardIndexRoute
  '/dashboard/auth/edit': typeof AdminLayoutDashboardAuthEditRoute
  '/dashboard/auth/view': typeof AdminLayoutDashboardAuthViewRoute
  '/dashboard/high-school/$id': typeof AdminLayoutDashboardHighSchoolIdRoute
  '/dashboard/packages/buy-packages': typeof AdminLayoutDashboardPackagesBuyPackagesRoute
  '/dashboard/violation-tops/violation-chart': typeof AdminLayoutDashboardViolationTopsViolationChartRoute
  '/dashboard/violation-tops/violation-in-class': typeof AdminLayoutDashboardViolationTopsViolationInClassRoute
  '/dashboard/violation-tops/violation-in-week': typeof AdminLayoutDashboardViolationTopsViolationInWeekRoute
  '/dashboard/violation-tops/violation-in-year': typeof AdminLayoutDashboardViolationTopsViolationInYearRoute
  '/dashboard/violation-tops/violation-top-class': typeof AdminLayoutDashboardViolationTopsViolationTopClassRoute
  '/dashboard/violation-tops/violation-top-student': typeof AdminLayoutDashboardViolationTopsViolationTopStudentRoute
  '/dashboard/violation-tops/violation-top-studentInClass': typeof AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute
  '/dashboard/violations/create-student': typeof AdminLayoutDashboardViolationsCreateStudentRoute
  '/dashboard/violations/create-supervisor': typeof AdminLayoutDashboardViolationsCreateSupervisorRoute
  '/dashboard/class-group': typeof AdminLayoutDashboardClassGroupIndexRoute
  '/dashboard/classes': typeof AdminLayoutDashboardClassesIndexRoute
  '/dashboard/disciplines': typeof AdminLayoutDashboardDisciplinesIndexRoute
  '/dashboard/evaluation-details': typeof AdminLayoutDashboardEvaluationDetailsIndexRoute
  '/dashboard/evaluation-tops': typeof AdminLayoutDashboardEvaluationTopsIndexRoute
  '/dashboard/evaluations': typeof AdminLayoutDashboardEvaluationsIndexRoute
  '/dashboard/high-school': typeof AdminLayoutDashboardHighSchoolIndexRoute
  '/dashboard/order': typeof AdminLayoutDashboardOrderIndexRoute
  '/dashboard/packages': typeof AdminLayoutDashboardPackagesIndexRoute
  '/dashboard/patrol-schedules': typeof AdminLayoutDashboardPatrolSchedulesIndexRoute
  '/dashboard/penalties': typeof AdminLayoutDashboardPenaltiesIndexRoute
  '/dashboard/registered-schools': typeof AdminLayoutDashboardRegisteredSchoolsIndexRoute
  '/dashboard/school-admin': typeof AdminLayoutDashboardSchoolAdminIndexRoute
  '/dashboard/school-configs': typeof AdminLayoutDashboardSchoolConfigsIndexRoute
  '/dashboard/school-year': typeof AdminLayoutDashboardSchoolYearIndexRoute
  '/dashboard/semester': typeof AdminLayoutDashboardSemesterIndexRoute
  '/dashboard/student-in-classes': typeof AdminLayoutDashboardStudentInClassesIndexRoute
  '/dashboard/student-supervisors': typeof AdminLayoutDashboardStudentSupervisorsIndexRoute
  '/dashboard/students': typeof AdminLayoutDashboardStudentsIndexRoute
  '/dashboard/teachers': typeof AdminLayoutDashboardTeachersIndexRoute
  '/dashboard/times': typeof AdminLayoutDashboardTimesIndexRoute
  '/dashboard/user': typeof AdminLayoutDashboardUserIndexRoute
  '/dashboard/violation-configs': typeof AdminLayoutDashboardViolationConfigsIndexRoute
  '/dashboard/violation-groups': typeof AdminLayoutDashboardViolationGroupsIndexRoute
  '/dashboard/violation-types': typeof AdminLayoutDashboardViolationTypesIndexRoute
  '/dashboard/violations': typeof AdminLayoutDashboardViolationsIndexRoute
  '/dashboard/year-packages': typeof AdminLayoutDashboardYearPackagesIndexRoute
  '/dashboard/classes/$id/history': typeof AdminLayoutDashboardClassesIdHistoryRoute
  '/dashboard/disciplines/$id/history': typeof AdminLayoutDashboardDisciplinesIdHistoryRoute
  '/dashboard/student-in-classes/$id/history': typeof AdminLayoutDashboardStudentInClassesIdHistoryRoute
  '/dashboard/violations/$id/edit': typeof AdminLayoutDashboardViolationsIdEditRoute
  '/dashboard/violations/$id/history': typeof AdminLayoutDashboardViolationsIdHistoryRoute
  '/dashboard/classes/$id': typeof AdminLayoutDashboardClassesIdIndexRoute
  '/dashboard/disciplines/$id': typeof AdminLayoutDashboardDisciplinesIdIndexRoute
  '/dashboard/violations/$id': typeof AdminLayoutDashboardViolationsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_admin-layout': typeof AdminLayoutRouteWithChildren
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_admin-layout/dashboard/$id': typeof AdminLayoutDashboardIdRoute
  '/_admin-layout/dashboard/analytics': typeof AdminLayoutDashboardAnalyticsRoute
  '/_admin-layout/dashboard/': typeof AdminLayoutDashboardIndexRoute
  '/_admin-layout/dashboard/auth/edit': typeof AdminLayoutDashboardAuthEditRoute
  '/_admin-layout/dashboard/auth/view': typeof AdminLayoutDashboardAuthViewRoute
  '/_admin-layout/dashboard/high-school/$id': typeof AdminLayoutDashboardHighSchoolIdRoute
  '/_admin-layout/dashboard/packages/buy-packages': typeof AdminLayoutDashboardPackagesBuyPackagesRoute
  '/_admin-layout/dashboard/violation-tops/violation-chart': typeof AdminLayoutDashboardViolationTopsViolationChartRoute
  '/_admin-layout/dashboard/violation-tops/violation-in-class': typeof AdminLayoutDashboardViolationTopsViolationInClassRoute
  '/_admin-layout/dashboard/violation-tops/violation-in-week': typeof AdminLayoutDashboardViolationTopsViolationInWeekRoute
  '/_admin-layout/dashboard/violation-tops/violation-in-year': typeof AdminLayoutDashboardViolationTopsViolationInYearRoute
  '/_admin-layout/dashboard/violation-tops/violation-top-class': typeof AdminLayoutDashboardViolationTopsViolationTopClassRoute
  '/_admin-layout/dashboard/violation-tops/violation-top-student': typeof AdminLayoutDashboardViolationTopsViolationTopStudentRoute
  '/_admin-layout/dashboard/violation-tops/violation-top-studentInClass': typeof AdminLayoutDashboardViolationTopsViolationTopStudentInClassRoute
  '/_admin-layout/dashboard/violations/create-student': typeof AdminLayoutDashboardViolationsCreateStudentRoute
  '/_admin-layout/dashboard/violations/create-supervisor': typeof AdminLayoutDashboardViolationsCreateSupervisorRoute
  '/_admin-layout/dashboard/class-group/': typeof AdminLayoutDashboardClassGroupIndexRoute
  '/_admin-layout/dashboard/classes/': typeof AdminLayoutDashboardClassesIndexRoute
  '/_admin-layout/dashboard/disciplines/': typeof AdminLayoutDashboardDisciplinesIndexRoute
  '/_admin-layout/dashboard/evaluation-details/': typeof AdminLayoutDashboardEvaluationDetailsIndexRoute
  '/_admin-layout/dashboard/evaluation-tops/': typeof AdminLayoutDashboardEvaluationTopsIndexRoute
  '/_admin-layout/dashboard/evaluations/': typeof AdminLayoutDashboardEvaluationsIndexRoute
  '/_admin-layout/dashboard/high-school/': typeof AdminLayoutDashboardHighSchoolIndexRoute
  '/_admin-layout/dashboard/order/': typeof AdminLayoutDashboardOrderIndexRoute
  '/_admin-layout/dashboard/packages/': typeof AdminLayoutDashboardPackagesIndexRoute
  '/_admin-layout/dashboard/patrol-schedules/': typeof AdminLayoutDashboardPatrolSchedulesIndexRoute
  '/_admin-layout/dashboard/penalties/': typeof AdminLayoutDashboardPenaltiesIndexRoute
  '/_admin-layout/dashboard/registered-schools/': typeof AdminLayoutDashboardRegisteredSchoolsIndexRoute
  '/_admin-layout/dashboard/school-admin/': typeof AdminLayoutDashboardSchoolAdminIndexRoute
  '/_admin-layout/dashboard/school-configs/': typeof AdminLayoutDashboardSchoolConfigsIndexRoute
  '/_admin-layout/dashboard/school-year/': typeof AdminLayoutDashboardSchoolYearIndexRoute
  '/_admin-layout/dashboard/semester/': typeof AdminLayoutDashboardSemesterIndexRoute
  '/_admin-layout/dashboard/student-in-classes/': typeof AdminLayoutDashboardStudentInClassesIndexRoute
  '/_admin-layout/dashboard/student-supervisors/': typeof AdminLayoutDashboardStudentSupervisorsIndexRoute
  '/_admin-layout/dashboard/students/': typeof AdminLayoutDashboardStudentsIndexRoute
  '/_admin-layout/dashboard/teachers/': typeof AdminLayoutDashboardTeachersIndexRoute
  '/_admin-layout/dashboard/times/': typeof AdminLayoutDashboardTimesIndexRoute
  '/_admin-layout/dashboard/user/': typeof AdminLayoutDashboardUserIndexRoute
  '/_admin-layout/dashboard/violation-configs/': typeof AdminLayoutDashboardViolationConfigsIndexRoute
  '/_admin-layout/dashboard/violation-groups/': typeof AdminLayoutDashboardViolationGroupsIndexRoute
  '/_admin-layout/dashboard/violation-types/': typeof AdminLayoutDashboardViolationTypesIndexRoute
  '/_admin-layout/dashboard/violations/': typeof AdminLayoutDashboardViolationsIndexRoute
  '/_admin-layout/dashboard/year-packages/': typeof AdminLayoutDashboardYearPackagesIndexRoute
  '/_admin-layout/dashboard/classes/$id/history': typeof AdminLayoutDashboardClassesIdHistoryRoute
  '/_admin-layout/dashboard/disciplines/$id/history': typeof AdminLayoutDashboardDisciplinesIdHistoryRoute
  '/_admin-layout/dashboard/student-in-classes/$id/history': typeof AdminLayoutDashboardStudentInClassesIdHistoryRoute
  '/_admin-layout/dashboard/violations/$id/edit': typeof AdminLayoutDashboardViolationsIdEditRoute
  '/_admin-layout/dashboard/violations/$id/history': typeof AdminLayoutDashboardViolationsIdHistoryRoute
  '/_admin-layout/dashboard/classes/$id/': typeof AdminLayoutDashboardClassesIdIndexRoute
  '/_admin-layout/dashboard/disciplines/$id/': typeof AdminLayoutDashboardDisciplinesIdIndexRoute
  '/_admin-layout/dashboard/violations/$id/': typeof AdminLayoutDashboardViolationsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/payment/failure'
    | '/payment/success'
    | '/dashboard/$id'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/auth/edit'
    | '/dashboard/auth/view'
    | '/dashboard/high-school/$id'
    | '/dashboard/packages/buy-packages'
    | '/dashboard/violation-tops/violation-chart'
    | '/dashboard/violation-tops/violation-in-class'
    | '/dashboard/violation-tops/violation-in-week'
    | '/dashboard/violation-tops/violation-in-year'
    | '/dashboard/violation-tops/violation-top-class'
    | '/dashboard/violation-tops/violation-top-student'
    | '/dashboard/violation-tops/violation-top-studentInClass'
    | '/dashboard/violations/create-student'
    | '/dashboard/violations/create-supervisor'
    | '/dashboard/class-group'
    | '/dashboard/classes'
    | '/dashboard/disciplines'
    | '/dashboard/evaluation-details'
    | '/dashboard/evaluation-tops'
    | '/dashboard/evaluations'
    | '/dashboard/high-school'
    | '/dashboard/order'
    | '/dashboard/packages'
    | '/dashboard/patrol-schedules'
    | '/dashboard/penalties'
    | '/dashboard/registered-schools'
    | '/dashboard/school-admin'
    | '/dashboard/school-configs'
    | '/dashboard/school-year'
    | '/dashboard/semester'
    | '/dashboard/student-in-classes'
    | '/dashboard/student-supervisors'
    | '/dashboard/students'
    | '/dashboard/teachers'
    | '/dashboard/times'
    | '/dashboard/user'
    | '/dashboard/violation-configs'
    | '/dashboard/violation-groups'
    | '/dashboard/violation-types'
    | '/dashboard/violations'
    | '/dashboard/year-packages'
    | '/dashboard/classes/$id/history'
    | '/dashboard/disciplines/$id/history'
    | '/dashboard/student-in-classes/$id/history'
    | '/dashboard/violations/$id/edit'
    | '/dashboard/violations/$id/history'
    | '/dashboard/classes/$id'
    | '/dashboard/disciplines/$id'
    | '/dashboard/violations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/payment/failure'
    | '/payment/success'
    | '/dashboard/$id'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/auth/edit'
    | '/dashboard/auth/view'
    | '/dashboard/high-school/$id'
    | '/dashboard/packages/buy-packages'
    | '/dashboard/violation-tops/violation-chart'
    | '/dashboard/violation-tops/violation-in-class'
    | '/dashboard/violation-tops/violation-in-week'
    | '/dashboard/violation-tops/violation-in-year'
    | '/dashboard/violation-tops/violation-top-class'
    | '/dashboard/violation-tops/violation-top-student'
    | '/dashboard/violation-tops/violation-top-studentInClass'
    | '/dashboard/violations/create-student'
    | '/dashboard/violations/create-supervisor'
    | '/dashboard/class-group'
    | '/dashboard/classes'
    | '/dashboard/disciplines'
    | '/dashboard/evaluation-details'
    | '/dashboard/evaluation-tops'
    | '/dashboard/evaluations'
    | '/dashboard/high-school'
    | '/dashboard/order'
    | '/dashboard/packages'
    | '/dashboard/patrol-schedules'
    | '/dashboard/penalties'
    | '/dashboard/registered-schools'
    | '/dashboard/school-admin'
    | '/dashboard/school-configs'
    | '/dashboard/school-year'
    | '/dashboard/semester'
    | '/dashboard/student-in-classes'
    | '/dashboard/student-supervisors'
    | '/dashboard/students'
    | '/dashboard/teachers'
    | '/dashboard/times'
    | '/dashboard/user'
    | '/dashboard/violation-configs'
    | '/dashboard/violation-groups'
    | '/dashboard/violation-types'
    | '/dashboard/violations'
    | '/dashboard/year-packages'
    | '/dashboard/classes/$id/history'
    | '/dashboard/disciplines/$id/history'
    | '/dashboard/student-in-classes/$id/history'
    | '/dashboard/violations/$id/edit'
    | '/dashboard/violations/$id/history'
    | '/dashboard/classes/$id'
    | '/dashboard/disciplines/$id'
    | '/dashboard/violations/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin-layout'
    | '/payment/failure'
    | '/payment/success'
    | '/_admin-layout/dashboard/$id'
    | '/_admin-layout/dashboard/analytics'
    | '/_admin-layout/dashboard/'
    | '/_admin-layout/dashboard/auth/edit'
    | '/_admin-layout/dashboard/auth/view'
    | '/_admin-layout/dashboard/high-school/$id'
    | '/_admin-layout/dashboard/packages/buy-packages'
    | '/_admin-layout/dashboard/violation-tops/violation-chart'
    | '/_admin-layout/dashboard/violation-tops/violation-in-class'
    | '/_admin-layout/dashboard/violation-tops/violation-in-week'
    | '/_admin-layout/dashboard/violation-tops/violation-in-year'
    | '/_admin-layout/dashboard/violation-tops/violation-top-class'
    | '/_admin-layout/dashboard/violation-tops/violation-top-student'
    | '/_admin-layout/dashboard/violation-tops/violation-top-studentInClass'
    | '/_admin-layout/dashboard/violations/create-student'
    | '/_admin-layout/dashboard/violations/create-supervisor'
    | '/_admin-layout/dashboard/class-group/'
    | '/_admin-layout/dashboard/classes/'
    | '/_admin-layout/dashboard/disciplines/'
    | '/_admin-layout/dashboard/evaluation-details/'
    | '/_admin-layout/dashboard/evaluation-tops/'
    | '/_admin-layout/dashboard/evaluations/'
    | '/_admin-layout/dashboard/high-school/'
    | '/_admin-layout/dashboard/order/'
    | '/_admin-layout/dashboard/packages/'
    | '/_admin-layout/dashboard/patrol-schedules/'
    | '/_admin-layout/dashboard/penalties/'
    | '/_admin-layout/dashboard/registered-schools/'
    | '/_admin-layout/dashboard/school-admin/'
    | '/_admin-layout/dashboard/school-configs/'
    | '/_admin-layout/dashboard/school-year/'
    | '/_admin-layout/dashboard/semester/'
    | '/_admin-layout/dashboard/student-in-classes/'
    | '/_admin-layout/dashboard/student-supervisors/'
    | '/_admin-layout/dashboard/students/'
    | '/_admin-layout/dashboard/teachers/'
    | '/_admin-layout/dashboard/times/'
    | '/_admin-layout/dashboard/user/'
    | '/_admin-layout/dashboard/violation-configs/'
    | '/_admin-layout/dashboard/violation-groups/'
    | '/_admin-layout/dashboard/violation-types/'
    | '/_admin-layout/dashboard/violations/'
    | '/_admin-layout/dashboard/year-packages/'
    | '/_admin-layout/dashboard/classes/$id/history'
    | '/_admin-layout/dashboard/disciplines/$id/history'
    | '/_admin-layout/dashboard/student-in-classes/$id/history'
    | '/_admin-layout/dashboard/violations/$id/edit'
    | '/_admin-layout/dashboard/violations/$id/history'
    | '/_admin-layout/dashboard/classes/$id/'
    | '/_admin-layout/dashboard/disciplines/$id/'
    | '/_admin-layout/dashboard/violations/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_admin-layout",
        "/payment/failure",
        "/payment/success"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_admin-layout": {
      "filePath": "_admin-layout.tsx",
      "children": [
        "/_admin-layout/dashboard/$id",
        "/_admin-layout/dashboard/analytics",
        "/_admin-layout/dashboard/",
        "/_admin-layout/dashboard/auth/edit",
        "/_admin-layout/dashboard/auth/view",
        "/_admin-layout/dashboard/high-school/$id",
        "/_admin-layout/dashboard/packages/buy-packages",
        "/_admin-layout/dashboard/violation-tops/violation-chart",
        "/_admin-layout/dashboard/violation-tops/violation-in-class",
        "/_admin-layout/dashboard/violation-tops/violation-in-week",
        "/_admin-layout/dashboard/violation-tops/violation-in-year",
        "/_admin-layout/dashboard/violation-tops/violation-top-class",
        "/_admin-layout/dashboard/violation-tops/violation-top-student",
        "/_admin-layout/dashboard/violation-tops/violation-top-studentInClass",
        "/_admin-layout/dashboard/violations/create-student",
        "/_admin-layout/dashboard/violations/create-supervisor",
        "/_admin-layout/dashboard/class-group/",
        "/_admin-layout/dashboard/classes/",
        "/_admin-layout/dashboard/disciplines/",
        "/_admin-layout/dashboard/evaluation-details/",
        "/_admin-layout/dashboard/evaluation-tops/",
        "/_admin-layout/dashboard/evaluations/",
        "/_admin-layout/dashboard/high-school/",
        "/_admin-layout/dashboard/order/",
        "/_admin-layout/dashboard/packages/",
        "/_admin-layout/dashboard/patrol-schedules/",
        "/_admin-layout/dashboard/penalties/",
        "/_admin-layout/dashboard/registered-schools/",
        "/_admin-layout/dashboard/school-admin/",
        "/_admin-layout/dashboard/school-configs/",
        "/_admin-layout/dashboard/school-year/",
        "/_admin-layout/dashboard/semester/",
        "/_admin-layout/dashboard/student-in-classes/",
        "/_admin-layout/dashboard/student-supervisors/",
        "/_admin-layout/dashboard/students/",
        "/_admin-layout/dashboard/teachers/",
        "/_admin-layout/dashboard/times/",
        "/_admin-layout/dashboard/user/",
        "/_admin-layout/dashboard/violation-configs/",
        "/_admin-layout/dashboard/violation-groups/",
        "/_admin-layout/dashboard/violation-types/",
        "/_admin-layout/dashboard/violations/",
        "/_admin-layout/dashboard/year-packages/",
        "/_admin-layout/dashboard/classes/$id/history",
        "/_admin-layout/dashboard/disciplines/$id/history",
        "/_admin-layout/dashboard/student-in-classes/$id/history",
        "/_admin-layout/dashboard/violations/$id/edit",
        "/_admin-layout/dashboard/violations/$id/history",
        "/_admin-layout/dashboard/classes/$id/",
        "/_admin-layout/dashboard/disciplines/$id/",
        "/_admin-layout/dashboard/violations/$id/"
      ]
    },
    "/payment/failure": {
      "filePath": "payment/failure.tsx"
    },
    "/payment/success": {
      "filePath": "payment/success.tsx"
    },
    "/_admin-layout/dashboard/$id": {
      "filePath": "_admin-layout.dashboard/$id.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/analytics": {
      "filePath": "_admin-layout.dashboard/analytics.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/": {
      "filePath": "_admin-layout.dashboard/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/auth/edit": {
      "filePath": "_admin-layout.dashboard/auth/edit.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/auth/view": {
      "filePath": "_admin-layout.dashboard/auth/view.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/high-school/$id": {
      "filePath": "_admin-layout.dashboard/high-school/$id.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/packages/buy-packages": {
      "filePath": "_admin-layout.dashboard/packages/buy-packages.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-chart": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-chart.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-in-class": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-in-class.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-in-week": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-in-week.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-in-year": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-in-year.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-top-class": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-top-class.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-top-student": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-top-student.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-tops/violation-top-studentInClass": {
      "filePath": "_admin-layout.dashboard/violation-tops/violation-top-studentInClass.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violations/create-student": {
      "filePath": "_admin-layout.dashboard/violations/create-student.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violations/create-supervisor": {
      "filePath": "_admin-layout.dashboard/violations/create-supervisor.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/class-group/": {
      "filePath": "_admin-layout.dashboard/class-group/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/classes/": {
      "filePath": "_admin-layout.dashboard/classes/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/disciplines/": {
      "filePath": "_admin-layout.dashboard/disciplines/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/evaluation-details/": {
      "filePath": "_admin-layout.dashboard/evaluation-details/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/evaluation-tops/": {
      "filePath": "_admin-layout.dashboard/evaluation-tops/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/evaluations/": {
      "filePath": "_admin-layout.dashboard/evaluations/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/high-school/": {
      "filePath": "_admin-layout.dashboard/high-school/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/order/": {
      "filePath": "_admin-layout.dashboard/order/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/packages/": {
      "filePath": "_admin-layout.dashboard/packages/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/patrol-schedules/": {
      "filePath": "_admin-layout.dashboard/patrol-schedules/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/penalties/": {
      "filePath": "_admin-layout.dashboard/penalties/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/registered-schools/": {
      "filePath": "_admin-layout.dashboard/registered-schools/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/school-admin/": {
      "filePath": "_admin-layout.dashboard/school-admin/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/school-configs/": {
      "filePath": "_admin-layout.dashboard/school-configs/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/school-year/": {
      "filePath": "_admin-layout.dashboard/school-year/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/semester/": {
      "filePath": "_admin-layout.dashboard/semester/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/student-in-classes/": {
      "filePath": "_admin-layout.dashboard/student-in-classes/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/student-supervisors/": {
      "filePath": "_admin-layout.dashboard/student-supervisors/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/students/": {
      "filePath": "_admin-layout.dashboard/students/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/teachers/": {
      "filePath": "_admin-layout.dashboard/teachers/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/times/": {
      "filePath": "_admin-layout.dashboard/times/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/user/": {
      "filePath": "_admin-layout.dashboard/user/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-configs/": {
      "filePath": "_admin-layout.dashboard/violation-configs/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-groups/": {
      "filePath": "_admin-layout.dashboard/violation-groups/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violation-types/": {
      "filePath": "_admin-layout.dashboard/violation-types/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violations/": {
      "filePath": "_admin-layout.dashboard/violations/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/year-packages/": {
      "filePath": "_admin-layout.dashboard/year-packages/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/classes/$id/history": {
      "filePath": "_admin-layout.dashboard/classes/$id/history.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/disciplines/$id/history": {
      "filePath": "_admin-layout.dashboard/disciplines/$id/history.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/student-in-classes/$id/history": {
      "filePath": "_admin-layout.dashboard/student-in-classes/$id/history.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violations/$id/edit": {
      "filePath": "_admin-layout.dashboard/violations/$id/edit.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violations/$id/history": {
      "filePath": "_admin-layout.dashboard/violations/$id/history.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/classes/$id/": {
      "filePath": "_admin-layout.dashboard/classes/$id/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/disciplines/$id/": {
      "filePath": "_admin-layout.dashboard/disciplines/$id/index.tsx",
      "parent": "/_admin-layout"
    },
    "/_admin-layout/dashboard/violations/$id/": {
      "filePath": "_admin-layout.dashboard/violations/$id/index.tsx",
      "parent": "/_admin-layout"
    }
  }
}
ROUTE_MANIFEST_END */
